server:
  port: ${port:8081}
spring:
  application:
    name: design-pattern
login:
  types:
    account: accountGranter
    sms: smsGranter
    we_chat: weChatGranter
logging:
  config: classpath:logback-spring.xml
